export interface IndonesiaRegion {
  value: string;
  label: string;
  province: string;
}

export const INDONESIA_REGIONS: IndonesiaRegion[] = [
  // ── Aceh ──────────────────────────────────────────────────────────────────
  { value: "banda-aceh", label: "Kota Banda Aceh", province: "Aceh" },
  { value: "sabang", label: "Kota Sabang", province: "Aceh" },
  { value: "langsa", label: "Kota Langsa", province: "Aceh" },
  { value: "lhokseumawe", label: "Kota Lhokseumawe", province: "Aceh" },
  { value: "subulussalam", label: "Kota Subulussalam", province: "Aceh" },
  { value: "aceh-besar", label: "Kabupaten Aceh Besar", province: "Aceh" },
  { value: "pidie", label: "Kabupaten Pidie", province: "Aceh" },
  { value: "pidie-jaya", label: "Kabupaten Pidie Jaya", province: "Aceh" },
  { value: "bireuen", label: "Kabupaten Bireuen", province: "Aceh" },
  { value: "aceh-utara", label: "Kabupaten Aceh Utara", province: "Aceh" },
  { value: "aceh-timur", label: "Kabupaten Aceh Timur", province: "Aceh" },
  { value: "aceh-tamiang", label: "Kabupaten Aceh Tamiang", province: "Aceh" },
  { value: "aceh-jaya", label: "Kabupaten Aceh Jaya", province: "Aceh" },
  { value: "aceh-barat", label: "Kabupaten Aceh Barat", province: "Aceh" },
  { value: "aceh-barat-daya", label: "Kabupaten Aceh Barat Daya", province: "Aceh" },
  { value: "nagan-raya", label: "Kabupaten Nagan Raya", province: "Aceh" },
  { value: "aceh-selatan", label: "Kabupaten Aceh Selatan", province: "Aceh" },
  { value: "aceh-singkil", label: "Kabupaten Aceh Singkil", province: "Aceh" },
  { value: "simeulue", label: "Kabupaten Simeulue", province: "Aceh" },
  { value: "gayo-lues", label: "Kabupaten Gayo Lues", province: "Aceh" },
  { value: "aceh-tengah", label: "Kabupaten Aceh Tengah", province: "Aceh" },
  { value: "bener-meriah", label: "Kabupaten Bener Meriah", province: "Aceh" },
  { value: "aceh-tenggara", label: "Kabupaten Aceh Tenggara", province: "Aceh" },

  // ── Sumatera Utara ────────────────────────────────────────────────────────
  { value: "medan", label: "Kota Medan", province: "Sumatera Utara" },
  { value: "binjai", label: "Kota Binjai", province: "Sumatera Utara" },
  { value: "pematang-siantar", label: "Kota Pematang Siantar", province: "Sumatera Utara" },
  { value: "tebing-tinggi-sumut", label: "Kota Tebing Tinggi", province: "Sumatera Utara" },
  { value: "tanjung-balai", label: "Kota Tanjung Balai", province: "Sumatera Utara" },
  { value: "sibolga", label: "Kota Sibolga", province: "Sumatera Utara" },
  { value: "padang-sidempuan", label: "Kota Padang Sidempuan", province: "Sumatera Utara" },
  { value: "gunungsitoli", label: "Kota Gunungsitoli", province: "Sumatera Utara" },
  { value: "deli-serdang", label: "Kabupaten Deli Serdang", province: "Sumatera Utara" },
  { value: "langkat", label: "Kabupaten Langkat", province: "Sumatera Utara" },
  { value: "karo", label: "Kabupaten Karo", province: "Sumatera Utara" },
  { value: "serdang-bedagai", label: "Kabupaten Serdang Bedagai", province: "Sumatera Utara" },
  { value: "batu-bara", label: "Kabupaten Batu Bara", province: "Sumatera Utara" },
  { value: "asahan", label: "Kabupaten Asahan", province: "Sumatera Utara" },
  { value: "labuhanbatu", label: "Kabupaten Labuhanbatu", province: "Sumatera Utara" },
  { value: "labuhanbatu-selatan", label: "Kabupaten Labuhanbatu Selatan", province: "Sumatera Utara" },
  { value: "labuhanbatu-utara", label: "Kabupaten Labuhanbatu Utara", province: "Sumatera Utara" },
  { value: "simalungun", label: "Kabupaten Simalungun", province: "Sumatera Utara" },
  { value: "dairi", label: "Kabupaten Dairi", province: "Sumatera Utara" },
  { value: "pakpak-bharat", label: "Kabupaten Pakpak Bharat", province: "Sumatera Utara" },
  { value: "toba-samosir", label: "Kabupaten Toba Samosir", province: "Sumatera Utara" },
  { value: "samosir", label: "Kabupaten Samosir", province: "Sumatera Utara" },
  { value: "humbang-hasundutan", label: "Kabupaten Humbang Hasundutan", province: "Sumatera Utara" },
  { value: "tapanuli-utara", label: "Kabupaten Tapanuli Utara", province: "Sumatera Utara" },
  { value: "tapanuli-tengah", label: "Kabupaten Tapanuli Tengah", province: "Sumatera Utara" },
  { value: "tapanuli-selatan", label: "Kabupaten Tapanuli Selatan", province: "Sumatera Utara" },
  { value: "mandailing-natal", label: "Kabupaten Mandailing Natal", province: "Sumatera Utara" },
  { value: "padang-lawas", label: "Kabupaten Padang Lawas", province: "Sumatera Utara" },
  { value: "padang-lawas-utara", label: "Kabupaten Padang Lawas Utara", province: "Sumatera Utara" },
  { value: "nias", label: "Kabupaten Nias", province: "Sumatera Utara" },
  { value: "nias-selatan", label: "Kabupaten Nias Selatan", province: "Sumatera Utara" },
  { value: "nias-utara", label: "Kabupaten Nias Utara", province: "Sumatera Utara" },
  { value: "nias-barat", label: "Kabupaten Nias Barat", province: "Sumatera Utara" },

  // ── Sumatera Barat ────────────────────────────────────────────────────────
  { value: "padang", label: "Kota Padang", province: "Sumatera Barat" },
  { value: "bukittinggi", label: "Kota Bukittinggi", province: "Sumatera Barat" },
  { value: "payakumbuh", label: "Kota Payakumbuh", province: "Sumatera Barat" },
  { value: "padang-panjang", label: "Kota Padang Panjang", province: "Sumatera Barat" },
  { value: "solok-kota", label: "Kota Solok", province: "Sumatera Barat" },
  { value: "sawahlunto", label: "Kota Sawahlunto", province: "Sumatera Barat" },
  { value: "pariaman", label: "Kota Pariaman", province: "Sumatera Barat" },
  { value: "pesisir-selatan", label: "Kabupaten Pesisir Selatan", province: "Sumatera Barat" },
  { value: "solok", label: "Kabupaten Solok", province: "Sumatera Barat" },
  { value: "solok-selatan", label: "Kabupaten Solok Selatan", province: "Sumatera Barat" },
  { value: "sijunjung", label: "Kabupaten Sijunjung", province: "Sumatera Barat" },
  { value: "dharmasraya", label: "Kabupaten Dharmasraya", province: "Sumatera Barat" },
  { value: "agam", label: "Kabupaten Agam", province: "Sumatera Barat" },
  { value: "lima-puluh-kota", label: "Kabupaten Lima Puluh Kota", province: "Sumatera Barat" },
  { value: "pasaman", label: "Kabupaten Pasaman", province: "Sumatera Barat" },
  { value: "pasaman-barat", label: "Kabupaten Pasaman Barat", province: "Sumatera Barat" },
  { value: "padang-pariaman", label: "Kabupaten Padang Pariaman", province: "Sumatera Barat" },
  { value: "tanah-datar", label: "Kabupaten Tanah Datar", province: "Sumatera Barat" },
  { value: "kepulauan-mentawai", label: "Kabupaten Kepulauan Mentawai", province: "Sumatera Barat" },

  // ── Riau ──────────────────────────────────────────────────────────────────
  { value: "pekanbaru", label: "Kota Pekanbaru", province: "Riau" },
  { value: "dumai", label: "Kota Dumai", province: "Riau" },
  { value: "kampar", label: "Kabupaten Kampar", province: "Riau" },
  { value: "rokan-hulu", label: "Kabupaten Rokan Hulu", province: "Riau" },
  { value: "bengkalis", label: "Kabupaten Bengkalis", province: "Riau" },
  { value: "siak", label: "Kabupaten Siak", province: "Riau" },
  { value: "pelalawan", label: "Kabupaten Pelalawan", province: "Riau" },
  { value: "indragiri-hulu", label: "Kabupaten Indragiri Hulu", province: "Riau" },
  { value: "indragiri-hilir", label: "Kabupaten Indragiri Hilir", province: "Riau" },
  { value: "rokan-hilir", label: "Kabupaten Rokan Hilir", province: "Riau" },
  { value: "kuantan-singingi", label: "Kabupaten Kuantan Singingi", province: "Riau" },
  { value: "kepulauan-meranti", label: "Kabupaten Kepulauan Meranti", province: "Riau" },

  // ── Kepulauan Riau ────────────────────────────────────────────────────────
  { value: "batam", label: "Kota Batam", province: "Kepulauan Riau" },
  { value: "tanjung-pinang", label: "Kota Tanjung Pinang", province: "Kepulauan Riau" },
  { value: "bintan", label: "Kabupaten Bintan", province: "Kepulauan Riau" },
  { value: "karimun", label: "Kabupaten Karimun", province: "Kepulauan Riau" },
  { value: "natuna", label: "Kabupaten Natuna", province: "Kepulauan Riau" },
  { value: "lingga", label: "Kabupaten Lingga", province: "Kepulauan Riau" },
  { value: "kepulauan-anambas", label: "Kabupaten Kepulauan Anambas", province: "Kepulauan Riau" },

  // ── Jambi ─────────────────────────────────────────────────────────────────
  { value: "jambi-kota", label: "Kota Jambi", province: "Jambi" },
  { value: "sungai-penuh", label: "Kota Sungai Penuh", province: "Jambi" },
  { value: "kerinci", label: "Kabupaten Kerinci", province: "Jambi" },
  { value: "merangin", label: "Kabupaten Merangin", province: "Jambi" },
  { value: "sarolangun", label: "Kabupaten Sarolangun", province: "Jambi" },
  { value: "batanghari", label: "Kabupaten Batanghari", province: "Jambi" },
  { value: "muaro-jambi", label: "Kabupaten Muaro Jambi", province: "Jambi" },
  { value: "tanjung-jabung-barat", label: "Kabupaten Tanjung Jabung Barat", province: "Jambi" },
  { value: "tanjung-jabung-timur", label: "Kabupaten Tanjung Jabung Timur", province: "Jambi" },
  { value: "tebo", label: "Kabupaten Tebo", province: "Jambi" },
  { value: "bungo", label: "Kabupaten Bungo", province: "Jambi" },

  // ── Bengkulu ──────────────────────────────────────────────────────────────
  { value: "bengkulu-kota", label: "Kota Bengkulu", province: "Bengkulu" },
  { value: "bengkulu-selatan", label: "Kabupaten Bengkulu Selatan", province: "Bengkulu" },
  { value: "bengkulu-utara", label: "Kabupaten Bengkulu Utara", province: "Bengkulu" },
  { value: "bengkulu-tengah", label: "Kabupaten Bengkulu Tengah", province: "Bengkulu" },
  { value: "rejang-lebong", label: "Kabupaten Rejang Lebong", province: "Bengkulu" },
  { value: "kepahiang", label: "Kabupaten Kepahiang", province: "Bengkulu" },
  { value: "lebong", label: "Kabupaten Lebong", province: "Bengkulu" },
  { value: "seluma", label: "Kabupaten Seluma", province: "Bengkulu" },
  { value: "kaur", label: "Kabupaten Kaur", province: "Bengkulu" },
  { value: "muko-muko", label: "Kabupaten Muko Muko", province: "Bengkulu" },

  // ── Sumatera Selatan ──────────────────────────────────────────────────────
  { value: "palembang", label: "Kota Palembang", province: "Sumatera Selatan" },
  { value: "prabumulih", label: "Kota Prabumulih", province: "Sumatera Selatan" },
  { value: "pagar-alam", label: "Kota Pagar Alam", province: "Sumatera Selatan" },
  { value: "lubuk-linggau", label: "Kota Lubuk Linggau", province: "Sumatera Selatan" },
  { value: "ogan-komering-ulu", label: "Kabupaten Ogan Komering Ulu", province: "Sumatera Selatan" },
  { value: "ogan-komering-ulu-timur", label: "Kabupaten Ogan Komering Ulu Timur", province: "Sumatera Selatan" },
  { value: "ogan-komering-ulu-selatan", label: "Kabupaten Ogan Komering Ulu Selatan", province: "Sumatera Selatan" },
  { value: "ogan-komering-ilir", label: "Kabupaten Ogan Komering Ilir", province: "Sumatera Selatan" },
  { value: "ogan-ilir", label: "Kabupaten Ogan Ilir", province: "Sumatera Selatan" },
  { value: "muara-enim", label: "Kabupaten Muara Enim", province: "Sumatera Selatan" },
  { value: "lahat", label: "Kabupaten Lahat", province: "Sumatera Selatan" },
  { value: "empat-lawang", label: "Kabupaten Empat Lawang", province: "Sumatera Selatan" },
  { value: "musi-rawas", label: "Kabupaten Musi Rawas", province: "Sumatera Selatan" },
  { value: "musi-rawas-utara", label: "Kabupaten Musi Rawas Utara", province: "Sumatera Selatan" },
  { value: "musi-banyuasin", label: "Kabupaten Musi Banyuasin", province: "Sumatera Selatan" },
  { value: "banyuasin", label: "Kabupaten Banyuasin", province: "Sumatera Selatan" },
  { value: "penukal-abab-lematang-ilir", label: "Kabupaten Penukal Abab Lematang Ilir", province: "Sumatera Selatan" },

  // ── Kepulauan Bangka Belitung ─────────────────────────────────────────────
  { value: "pangkal-pinang", label: "Kota Pangkal Pinang", province: "Kepulauan Bangka Belitung" },
  { value: "bangka", label: "Kabupaten Bangka", province: "Kepulauan Bangka Belitung" },
  { value: "bangka-tengah", label: "Kabupaten Bangka Tengah", province: "Kepulauan Bangka Belitung" },
  { value: "bangka-selatan", label: "Kabupaten Bangka Selatan", province: "Kepulauan Bangka Belitung" },
  { value: "bangka-barat", label: "Kabupaten Bangka Barat", province: "Kepulauan Bangka Belitung" },
  { value: "belitung", label: "Kabupaten Belitung", province: "Kepulauan Bangka Belitung" },
  { value: "belitung-timur", label: "Kabupaten Belitung Timur", province: "Kepulauan Bangka Belitung" },

  // ── Lampung ───────────────────────────────────────────────────────────────
  { value: "bandar-lampung", label: "Kota Bandar Lampung", province: "Lampung" },
  { value: "metro", label: "Kota Metro", province: "Lampung" },
  { value: "lampung-selatan", label: "Kabupaten Lampung Selatan", province: "Lampung" },
  { value: "lampung-tengah", label: "Kabupaten Lampung Tengah", province: "Lampung" },
  { value: "lampung-utara", label: "Kabupaten Lampung Utara", province: "Lampung" },
  { value: "lampung-barat", label: "Kabupaten Lampung Barat", province: "Lampung" },
  { value: "lampung-timur", label: "Kabupaten Lampung Timur", province: "Lampung" },
  { value: "pesawaran", label: "Kabupaten Pesawaran", province: "Lampung" },
  { value: "pringsewu", label: "Kabupaten Pringsewu", province: "Lampung" },
  { value: "tanggamus", label: "Kabupaten Tanggamus", province: "Lampung" },
  { value: "tulang-bawang", label: "Kabupaten Tulang Bawang", province: "Lampung" },
  { value: "tulang-bawang-barat", label: "Kabupaten Tulang Bawang Barat", province: "Lampung" },
  { value: "mesuji", label: "Kabupaten Mesuji", province: "Lampung" },
  { value: "pesisir-barat", label: "Kabupaten Pesisir Barat", province: "Lampung" },
  { value: "way-kanan", label: "Kabupaten Way Kanan", province: "Lampung" },

  // ── Banten ────────────────────────────────────────────────────────────────
  { value: "tangerang-kota", label: "Kota Tangerang", province: "Banten" },
  { value: "tangerang-selatan", label: "Kota Tangerang Selatan", province: "Banten" },
  { value: "serang-kota", label: "Kota Serang", province: "Banten" },
  { value: "cilegon", label: "Kota Cilegon", province: "Banten" },
  { value: "tangerang", label: "Kabupaten Tangerang", province: "Banten" },
  { value: "serang", label: "Kabupaten Serang", province: "Banten" },
  { value: "pandeglang", label: "Kabupaten Pandeglang", province: "Banten" },
  { value: "lebak", label: "Kabupaten Lebak", province: "Banten" },

  // ── DKI Jakarta ───────────────────────────────────────────────────────────
  { value: "jakarta-pusat", label: "Kota Jakarta Pusat", province: "DKI Jakarta" },
  { value: "jakarta-utara", label: "Kota Jakarta Utara", province: "DKI Jakarta" },
  { value: "jakarta-barat", label: "Kota Jakarta Barat", province: "DKI Jakarta" },
  { value: "jakarta-selatan", label: "Kota Jakarta Selatan", province: "DKI Jakarta" },
  { value: "jakarta-timur", label: "Kota Jakarta Timur", province: "DKI Jakarta" },
  { value: "kepulauan-seribu", label: "Kabupaten Kepulauan Seribu", province: "DKI Jakarta" },

  // ── Jawa Barat ────────────────────────────────────────────────────────────
  { value: "bandung-kota", label: "Kota Bandung", province: "Jawa Barat" },
  { value: "bekasi-kota", label: "Kota Bekasi", province: "Jawa Barat" },
  { value: "depok", label: "Kota Depok", province: "Jawa Barat" },
  { value: "bogor-kota", label: "Kota Bogor", province: "Jawa Barat" },
  { value: "cimahi", label: "Kota Cimahi", province: "Jawa Barat" },
  { value: "tasikmalaya-kota", label: "Kota Tasikmalaya", province: "Jawa Barat" },
  { value: "cirebon-kota", label: "Kota Cirebon", province: "Jawa Barat" },
  { value: "sukabumi-kota", label: "Kota Sukabumi", province: "Jawa Barat" },
  { value: "banjar", label: "Kota Banjar", province: "Jawa Barat" },
  { value: "bogor", label: "Kabupaten Bogor", province: "Jawa Barat" },
  { value: "bekasi", label: "Kabupaten Bekasi", province: "Jawa Barat" },
  { value: "karawang", label: "Kabupaten Karawang", province: "Jawa Barat" },
  { value: "purwakarta", label: "Kabupaten Purwakarta", province: "Jawa Barat" },
  { value: "subang", label: "Kabupaten Subang", province: "Jawa Barat" },
  { value: "bandung", label: "Kabupaten Bandung", province: "Jawa Barat" },
  { value: "bandung-barat", label: "Kabupaten Bandung Barat", province: "Jawa Barat" },
  { value: "sumedang", label: "Kabupaten Sumedang", province: "Jawa Barat" },
  { value: "indramayu", label: "Kabupaten Indramayu", province: "Jawa Barat" },
  { value: "cirebon", label: "Kabupaten Cirebon", province: "Jawa Barat" },
  { value: "kuningan", label: "Kabupaten Kuningan", province: "Jawa Barat" },
  { value: "majalengka", label: "Kabupaten Majalengka", province: "Jawa Barat" },
  { value: "sukabumi", label: "Kabupaten Sukabumi", province: "Jawa Barat" },
  { value: "cianjur", label: "Kabupaten Cianjur", province: "Jawa Barat" },
  { value: "garut", label: "Kabupaten Garut", province: "Jawa Barat" },
  { value: "tasikmalaya", label: "Kabupaten Tasikmalaya", province: "Jawa Barat" },
  { value: "ciamis", label: "Kabupaten Ciamis", province: "Jawa Barat" },
  { value: "pangandaran", label: "Kabupaten Pangandaran", province: "Jawa Barat" },

  // ── Jawa Tengah ───────────────────────────────────────────────────────────
  { value: "semarang-kota", label: "Kota Semarang", province: "Jawa Tengah" },
  { value: "surakarta", label: "Kota Surakarta", province: "Jawa Tengah" },
  { value: "salatiga", label: "Kota Salatiga", province: "Jawa Tengah" },
  { value: "pekalongan-kota", label: "Kota Pekalongan", province: "Jawa Tengah" },
  { value: "tegal-kota", label: "Kota Tegal", province: "Jawa Tengah" },
  { value: "magelang-kota", label: "Kota Magelang", province: "Jawa Tengah" },
  { value: "semarang", label: "Kabupaten Semarang", province: "Jawa Tengah" },
  { value: "kendal", label: "Kabupaten Kendal", province: "Jawa Tengah" },
  { value: "demak", label: "Kabupaten Demak", province: "Jawa Tengah" },
  { value: "grobogan", label: "Kabupaten Grobogan", province: "Jawa Tengah" },
  { value: "kudus", label: "Kabupaten Kudus", province: "Jawa Tengah" },
  { value: "jepara", label: "Kabupaten Jepara", province: "Jawa Tengah" },
  { value: "pati", label: "Kabupaten Pati", province: "Jawa Tengah" },
  { value: "rembang", label: "Kabupaten Rembang", province: "Jawa Tengah" },
  { value: "blora", label: "Kabupaten Blora", province: "Jawa Tengah" },
  { value: "boyolali", label: "Kabupaten Boyolali", province: "Jawa Tengah" },
  { value: "klaten", label: "Kabupaten Klaten", province: "Jawa Tengah" },
  { value: "sukoharjo", label: "Kabupaten Sukoharjo", province: "Jawa Tengah" },
  { value: "karanganyar", label: "Kabupaten Karanganyar", province: "Jawa Tengah" },
  { value: "sragen", label: "Kabupaten Sragen", province: "Jawa Tengah" },
  { value: "wonogiri", label: "Kabupaten Wonogiri", province: "Jawa Tengah" },
  { value: "magelang", label: "Kabupaten Magelang", province: "Jawa Tengah" },
  { value: "temanggung", label: "Kabupaten Temanggung", province: "Jawa Tengah" },
  { value: "wonosobo", label: "Kabupaten Wonosobo", province: "Jawa Tengah" },
  { value: "purworejo", label: "Kabupaten Purworejo", province: "Jawa Tengah" },
  { value: "kebumen", label: "Kabupaten Kebumen", province: "Jawa Tengah" },
  { value: "cilacap", label: "Kabupaten Cilacap", province: "Jawa Tengah" },
  { value: "banyumas", label: "Kabupaten Banyumas", province: "Jawa Tengah" },
  { value: "purbalingga", label: "Kabupaten Purbalingga", province: "Jawa Tengah" },
  { value: "banjarnegara", label: "Kabupaten Banjarnegara", province: "Jawa Tengah" },
  { value: "pekalongan", label: "Kabupaten Pekalongan", province: "Jawa Tengah" },
  { value: "batang", label: "Kabupaten Batang", province: "Jawa Tengah" },
  { value: "pemalang", label: "Kabupaten Pemalang", province: "Jawa Tengah" },
  { value: "tegal", label: "Kabupaten Tegal", province: "Jawa Tengah" },
  { value: "brebes", label: "Kabupaten Brebes", province: "Jawa Tengah" },

  // ── DI Yogyakarta ─────────────────────────────────────────────────────────
  { value: "yogyakarta", label: "Kota Yogyakarta", province: "DI Yogyakarta" },
  { value: "sleman", label: "Kabupaten Sleman", province: "DI Yogyakarta" },
  { value: "bantul", label: "Kabupaten Bantul", province: "DI Yogyakarta" },
  { value: "gunung-kidul", label: "Kabupaten Gunung Kidul", province: "DI Yogyakarta" },
  { value: "kulon-progo", label: "Kabupaten Kulon Progo", province: "DI Yogyakarta" },

  // ── Jawa Timur ────────────────────────────────────────────────────────────
  { value: "surabaya", label: "Kota Surabaya", province: "Jawa Timur" },
  { value: "malang-kota", label: "Kota Malang", province: "Jawa Timur" },
  { value: "madiun-kota", label: "Kota Madiun", province: "Jawa Timur" },
  { value: "kediri-kota", label: "Kota Kediri", province: "Jawa Timur" },
  { value: "blitar-kota", label: "Kota Blitar", province: "Jawa Timur" },
  { value: "mojokerto-kota", label: "Kota Mojokerto", province: "Jawa Timur" },
  { value: "probolinggo-kota", label: "Kota Probolinggo", province: "Jawa Timur" },
  { value: "pasuruan-kota", label: "Kota Pasuruan", province: "Jawa Timur" },
  { value: "batu", label: "Kota Batu", province: "Jawa Timur" },
  { value: "gresik", label: "Kabupaten Gresik", province: "Jawa Timur" },
  { value: "sidoarjo", label: "Kabupaten Sidoarjo", province: "Jawa Timur" },
  { value: "mojokerto", label: "Kabupaten Mojokerto", province: "Jawa Timur" },
  { value: "jombang", label: "Kabupaten Jombang", province: "Jawa Timur" },
  { value: "lamongan", label: "Kabupaten Lamongan", province: "Jawa Timur" },
  { value: "tuban", label: "Kabupaten Tuban", province: "Jawa Timur" },
  { value: "bojonegoro", label: "Kabupaten Bojonegoro", province: "Jawa Timur" },
  { value: "ngawi", label: "Kabupaten Ngawi", province: "Jawa Timur" },
  { value: "magetan", label: "Kabupaten Magetan", province: "Jawa Timur" },
  { value: "madiun", label: "Kabupaten Madiun", province: "Jawa Timur" },
  { value: "nganjuk", label: "Kabupaten Nganjuk", province: "Jawa Timur" },
  { value: "kediri", label: "Kabupaten Kediri", province: "Jawa Timur" },
  { value: "tulungagung", label: "Kabupaten Tulungagung", province: "Jawa Timur" },
  { value: "blitar", label: "Kabupaten Blitar", province: "Jawa Timur" },
  { value: "malang", label: "Kabupaten Malang", province: "Jawa Timur" },
  { value: "pasuruan", label: "Kabupaten Pasuruan", province: "Jawa Timur" },
  { value: "probolinggo", label: "Kabupaten Probolinggo", province: "Jawa Timur" },
  { value: "lumajang", label: "Kabupaten Lumajang", province: "Jawa Timur" },
  { value: "jember", label: "Kabupaten Jember", province: "Jawa Timur" },
  { value: "banyuwangi", label: "Kabupaten Banyuwangi", province: "Jawa Timur" },
  { value: "bondowoso", label: "Kabupaten Bondowoso", province: "Jawa Timur" },
  { value: "situbondo", label: "Kabupaten Situbondo", province: "Jawa Timur" },
  { value: "trenggalek", label: "Kabupaten Trenggalek", province: "Jawa Timur" },
  { value: "ponorogo", label: "Kabupaten Ponorogo", province: "Jawa Timur" },
  { value: "pacitan", label: "Kabupaten Pacitan", province: "Jawa Timur" },
  { value: "pamekasan", label: "Kabupaten Pamekasan", province: "Jawa Timur" },
  { value: "sumenep", label: "Kabupaten Sumenep", province: "Jawa Timur" },
  { value: "sampang", label: "Kabupaten Sampang", province: "Jawa Timur" },
  { value: "bangkalan", label: "Kabupaten Bangkalan", province: "Jawa Timur" },

  // ── Bali ──────────────────────────────────────────────────────────────────
  { value: "denpasar", label: "Kota Denpasar", province: "Bali" },
  { value: "badung", label: "Kabupaten Badung", province: "Bali" },
  { value: "gianyar", label: "Kabupaten Gianyar", province: "Bali" },
  { value: "tabanan", label: "Kabupaten Tabanan", province: "Bali" },
  { value: "jembrana", label: "Kabupaten Jembrana", province: "Bali" },
  { value: "buleleng", label: "Kabupaten Buleleng", province: "Bali" },
  { value: "bangli", label: "Kabupaten Bangli", province: "Bali" },
  { value: "klungkung", label: "Kabupaten Klungkung", province: "Bali" },
  { value: "karangasem", label: "Kabupaten Karangasem", province: "Bali" },

  // ── Nusa Tenggara Barat ───────────────────────────────────────────────────
  { value: "mataram", label: "Kota Mataram", province: "Nusa Tenggara Barat" },
  { value: "bima-kota", label: "Kota Bima", province: "Nusa Tenggara Barat" },
  { value: "lombok-barat", label: "Kabupaten Lombok Barat", province: "Nusa Tenggara Barat" },
  { value: "lombok-tengah", label: "Kabupaten Lombok Tengah", province: "Nusa Tenggara Barat" },
  { value: "lombok-timur", label: "Kabupaten Lombok Timur", province: "Nusa Tenggara Barat" },
  { value: "lombok-utara", label: "Kabupaten Lombok Utara", province: "Nusa Tenggara Barat" },
  { value: "sumbawa", label: "Kabupaten Sumbawa", province: "Nusa Tenggara Barat" },
  { value: "sumbawa-barat", label: "Kabupaten Sumbawa Barat", province: "Nusa Tenggara Barat" },
  { value: "dompu", label: "Kabupaten Dompu", province: "Nusa Tenggara Barat" },
  { value: "bima", label: "Kabupaten Bima", province: "Nusa Tenggara Barat" },

  // ── Nusa Tenggara Timur ───────────────────────────────────────────────────
  { value: "kupang-kota", label: "Kota Kupang", province: "Nusa Tenggara Timur" },
  { value: "kupang", label: "Kabupaten Kupang", province: "Nusa Tenggara Timur" },
  { value: "timor-tengah-selatan", label: "Kabupaten Timor Tengah Selatan", province: "Nusa Tenggara Timur" },
  { value: "timor-tengah-utara", label: "Kabupaten Timor Tengah Utara", province: "Nusa Tenggara Timur" },
  { value: "belu", label: "Kabupaten Belu", province: "Nusa Tenggara Timur" },
  { value: "malaka", label: "Kabupaten Malaka", province: "Nusa Tenggara Timur" },
  { value: "alor", label: "Kabupaten Alor", province: "Nusa Tenggara Timur" },
  { value: "lembata", label: "Kabupaten Lembata", province: "Nusa Tenggara Timur" },
  { value: "flores-timur", label: "Kabupaten Flores Timur", province: "Nusa Tenggara Timur" },
  { value: "sikka", label: "Kabupaten Sikka", province: "Nusa Tenggara Timur" },
  { value: "ende", label: "Kabupaten Ende", province: "Nusa Tenggara Timur" },
  { value: "ngada", label: "Kabupaten Ngada", province: "Nusa Tenggara Timur" },
  { value: "nagekeo", label: "Kabupaten Nagekeo", province: "Nusa Tenggara Timur" },
  { value: "manggarai", label: "Kabupaten Manggarai", province: "Nusa Tenggara Timur" },
  { value: "manggarai-barat", label: "Kabupaten Manggarai Barat", province: "Nusa Tenggara Timur" },
  { value: "manggarai-timur", label: "Kabupaten Manggarai Timur", province: "Nusa Tenggara Timur" },
  { value: "sumba-barat", label: "Kabupaten Sumba Barat", province: "Nusa Tenggara Timur" },
  { value: "sumba-barat-daya", label: "Kabupaten Sumba Barat Daya", province: "Nusa Tenggara Timur" },
  { value: "sumba-tengah", label: "Kabupaten Sumba Tengah", province: "Nusa Tenggara Timur" },
  { value: "sumba-timur", label: "Kabupaten Sumba Timur", province: "Nusa Tenggara Timur" },
  { value: "rote-ndao", label: "Kabupaten Rote Ndao", province: "Nusa Tenggara Timur" },
  { value: "sabu-raijua", label: "Kabupaten Sabu Raijua", province: "Nusa Tenggara Timur" },

  // ── Kalimantan Barat ──────────────────────────────────────────────────────
  { value: "pontianak", label: "Kota Pontianak", province: "Kalimantan Barat" },
  { value: "singkawang", label: "Kota Singkawang", province: "Kalimantan Barat" },
  { value: "sambas", label: "Kabupaten Sambas", province: "Kalimantan Barat" },
  { value: "bengkayang", label: "Kabupaten Bengkayang", province: "Kalimantan Barat" },
  { value: "landak", label: "Kabupaten Landak", province: "Kalimantan Barat" },
  { value: "mempawah", label: "Kabupaten Mempawah", province: "Kalimantan Barat" },
  { value: "sanggau", label: "Kabupaten Sanggau", province: "Kalimantan Barat" },
  { value: "sekadau", label: "Kabupaten Sekadau", province: "Kalimantan Barat" },
  { value: "sintang", label: "Kabupaten Sintang", province: "Kalimantan Barat" },
  { value: "melawi", label: "Kabupaten Melawi", province: "Kalimantan Barat" },
  { value: "ketapang", label: "Kabupaten Ketapang", province: "Kalimantan Barat" },
  { value: "kayong-utara", label: "Kabupaten Kayong Utara", province: "Kalimantan Barat" },
  { value: "kapuas-hulu", label: "Kabupaten Kapuas Hulu", province: "Kalimantan Barat" },
  { value: "kubu-raya", label: "Kabupaten Kubu Raya", province: "Kalimantan Barat" },

  // ── Kalimantan Tengah ─────────────────────────────────────────────────────
  { value: "palangkaraya", label: "Kota Palangka Raya", province: "Kalimantan Tengah" },
  { value: "kotawaringin-barat", label: "Kabupaten Kotawaringin Barat", province: "Kalimantan Tengah" },
  { value: "kotawaringin-timur", label: "Kabupaten Kotawaringin Timur", province: "Kalimantan Tengah" },
  { value: "kapuas", label: "Kabupaten Kapuas", province: "Kalimantan Tengah" },
  { value: "barito-selatan", label: "Kabupaten Barito Selatan", province: "Kalimantan Tengah" },
  { value: "barito-utara", label: "Kabupaten Barito Utara", province: "Kalimantan Tengah" },
  { value: "barito-timur", label: "Kabupaten Barito Timur", province: "Kalimantan Tengah" },
  { value: "murung-raya", label: "Kabupaten Murung Raya", province: "Kalimantan Tengah" },
  { value: "gunung-mas", label: "Kabupaten Gunung Mas", province: "Kalimantan Tengah" },
  { value: "katingan", label: "Kabupaten Katingan", province: "Kalimantan Tengah" },
  { value: "seruyan", label: "Kabupaten Seruyan", province: "Kalimantan Tengah" },
  { value: "lamandau", label: "Kabupaten Lamandau", province: "Kalimantan Tengah" },
  { value: "sukamara", label: "Kabupaten Sukamara", province: "Kalimantan Tengah" },
  { value: "pulang-pisau", label: "Kabupaten Pulang Pisau", province: "Kalimantan Tengah" },

  // ── Kalimantan Selatan ────────────────────────────────────────────────────
  { value: "banjarmasin", label: "Kota Banjarmasin", province: "Kalimantan Selatan" },
  { value: "banjarbaru", label: "Kota Banjarbaru", province: "Kalimantan Selatan" },
  { value: "banjar", label: "Kabupaten Banjar", province: "Kalimantan Selatan" },
  { value: "barito-kuala", label: "Kabupaten Barito Kuala", province: "Kalimantan Selatan" },
  { value: "tapin", label: "Kabupaten Tapin", province: "Kalimantan Selatan" },
  { value: "hulu-sungai-selatan", label: "Kabupaten Hulu Sungai Selatan", province: "Kalimantan Selatan" },
  { value: "hulu-sungai-tengah", label: "Kabupaten Hulu Sungai Tengah", province: "Kalimantan Selatan" },
  { value: "hulu-sungai-utara", label: "Kabupaten Hulu Sungai Utara", province: "Kalimantan Selatan" },
  { value: "balangan", label: "Kabupaten Balangan", province: "Kalimantan Selatan" },
  { value: "tabalong", label: "Kabupaten Tabalong", province: "Kalimantan Selatan" },
  { value: "tanah-laut", label: "Kabupaten Tanah Laut", province: "Kalimantan Selatan" },
  { value: "tanah-bumbu", label: "Kabupaten Tanah Bumbu", province: "Kalimantan Selatan" },
  { value: "kotabaru", label: "Kabupaten Kotabaru", province: "Kalimantan Selatan" },

  // ── Kalimantan Timur ──────────────────────────────────────────────────────
  { value: "samarinda", label: "Kota Samarinda", province: "Kalimantan Timur" },
  { value: "balikpapan", label: "Kota Balikpapan", province: "Kalimantan Timur" },
  { value: "bontang", label: "Kota Bontang", province: "Kalimantan Timur" },
  { value: "kutai-kartanegara", label: "Kabupaten Kutai Kartanegara", province: "Kalimantan Timur" },
  { value: "kutai-barat", label: "Kabupaten Kutai Barat", province: "Kalimantan Timur" },
  { value: "kutai-timur", label: "Kabupaten Kutai Timur", province: "Kalimantan Timur" },
  { value: "berau", label: "Kabupaten Berau", province: "Kalimantan Timur" },
  { value: "penajam-paser-utara", label: "Kabupaten Penajam Paser Utara", province: "Kalimantan Timur" },
  { value: "paser", label: "Kabupaten Paser", province: "Kalimantan Timur" },
  { value: "mahakam-ulu", label: "Kabupaten Mahakam Ulu", province: "Kalimantan Timur" },

  // ── Kalimantan Utara ──────────────────────────────────────────────────────
  { value: "tarakan", label: "Kota Tarakan", province: "Kalimantan Utara" },
  { value: "bulungan", label: "Kabupaten Bulungan", province: "Kalimantan Utara" },
  { value: "malinau", label: "Kabupaten Malinau", province: "Kalimantan Utara" },
  { value: "nunukan", label: "Kabupaten Nunukan", province: "Kalimantan Utara" },
  { value: "tana-tidung", label: "Kabupaten Tana Tidung", province: "Kalimantan Utara" },

  // ── Sulawesi Utara ────────────────────────────────────────────────────────
  { value: "manado", label: "Kota Manado", province: "Sulawesi Utara" },
  { value: "bitung", label: "Kota Bitung", province: "Sulawesi Utara" },
  { value: "tomohon", label: "Kota Tomohon", province: "Sulawesi Utara" },
  { value: "kotamobagu", label: "Kota Kotamobagu", province: "Sulawesi Utara" },
  { value: "minahasa", label: "Kabupaten Minahasa", province: "Sulawesi Utara" },
  { value: "minahasa-utara", label: "Kabupaten Minahasa Utara", province: "Sulawesi Utara" },
  { value: "minahasa-selatan", label: "Kabupaten Minahasa Selatan", province: "Sulawesi Utara" },
  { value: "minahasa-tenggara", label: "Kabupaten Minahasa Tenggara", province: "Sulawesi Utara" },
  { value: "bolaang-mongondow", label: "Kabupaten Bolaang Mongondow", province: "Sulawesi Utara" },
  { value: "bolaang-mongondow-utara", label: "Kabupaten Bolaang Mongondow Utara", province: "Sulawesi Utara" },
  { value: "bolaang-mongondow-selatan", label: "Kabupaten Bolaang Mongondow Selatan", province: "Sulawesi Utara" },
  { value: "bolaang-mongondow-timur", label: "Kabupaten Bolaang Mongondow Timur", province: "Sulawesi Utara" },
  { value: "sangihe", label: "Kabupaten Kepulauan Sangihe", province: "Sulawesi Utara" },
  { value: "sitaro", label: "Kabupaten Kepulauan Sitaro", province: "Sulawesi Utara" },
  { value: "talaud", label: "Kabupaten Kepulauan Talaud", province: "Sulawesi Utara" },

  // ── Gorontalo ─────────────────────────────────────────────────────────────
  { value: "gorontalo-kota", label: "Kota Gorontalo", province: "Gorontalo" },
  { value: "gorontalo", label: "Kabupaten Gorontalo", province: "Gorontalo" },
  { value: "gorontalo-utara", label: "Kabupaten Gorontalo Utara", province: "Gorontalo" },
  { value: "boalemo", label: "Kabupaten Boalemo", province: "Gorontalo" },
  { value: "pohuwato", label: "Kabupaten Pohuwato", province: "Gorontalo" },
  { value: "bone-bolango", label: "Kabupaten Bone Bolango", province: "Gorontalo" },

  // ── Sulawesi Tengah ───────────────────────────────────────────────────────
  { value: "palu", label: "Kota Palu", province: "Sulawesi Tengah" },
  { value: "donggala", label: "Kabupaten Donggala", province: "Sulawesi Tengah" },
  { value: "parigi-moutong", label: "Kabupaten Parigi Moutong", province: "Sulawesi Tengah" },
  { value: "poso", label: "Kabupaten Poso", province: "Sulawesi Tengah" },
  { value: "tojo-una-una", label: "Kabupaten Tojo Una-Una", province: "Sulawesi Tengah" },
  { value: "banggai", label: "Kabupaten Banggai", province: "Sulawesi Tengah" },
  { value: "banggai-kepulauan", label: "Kabupaten Banggai Kepulauan", province: "Sulawesi Tengah" },
  { value: "banggai-laut", label: "Kabupaten Banggai Laut", province: "Sulawesi Tengah" },
  { value: "buol", label: "Kabupaten Buol", province: "Sulawesi Tengah" },
  { value: "toli-toli", label: "Kabupaten Toli-Toli", province: "Sulawesi Tengah" },
  { value: "morowali", label: "Kabupaten Morowali", province: "Sulawesi Tengah" },
  { value: "morowali-utara", label: "Kabupaten Morowali Utara", province: "Sulawesi Tengah" },
  { value: "sigi", label: "Kabupaten Sigi", province: "Sulawesi Tengah" },

  // ── Sulawesi Barat ────────────────────────────────────────────────────────
  { value: "mamuju", label: "Kabupaten Mamuju", province: "Sulawesi Barat" },
  { value: "mamuju-tengah", label: "Kabupaten Mamuju Tengah", province: "Sulawesi Barat" },
  { value: "mamuju-utara", label: "Kabupaten Mamuju Utara", province: "Sulawesi Barat" },
  { value: "majene", label: "Kabupaten Majene", province: "Sulawesi Barat" },
  { value: "polewali-mandar", label: "Kabupaten Polewali Mandar", province: "Sulawesi Barat" },
  { value: "mamasa", label: "Kabupaten Mamasa", province: "Sulawesi Barat" },

  // ── Sulawesi Selatan ──────────────────────────────────────────────────────
  { value: "makassar", label: "Kota Makassar", province: "Sulawesi Selatan" },
  { value: "parepare", label: "Kota Parepare", province: "Sulawesi Selatan" },
  { value: "palopo", label: "Kota Palopo", province: "Sulawesi Selatan" },
  { value: "gowa", label: "Kabupaten Gowa", province: "Sulawesi Selatan" },
  { value: "maros", label: "Kabupaten Maros", province: "Sulawesi Selatan" },
  { value: "pangkajene-dan-kepulauan", label: "Kabupaten Pangkajene dan Kepulauan", province: "Sulawesi Selatan" },
  { value: "barru", label: "Kabupaten Barru", province: "Sulawesi Selatan" },
  { value: "bone", label: "Kabupaten Bone", province: "Sulawesi Selatan" },
  { value: "sinjai", label: "Kabupaten Sinjai", province: "Sulawesi Selatan" },
  { value: "bulukumba", label: "Kabupaten Bulukumba", province: "Sulawesi Selatan" },
  { value: "bantaeng", label: "Kabupaten Bantaeng", province: "Sulawesi Selatan" },
  { value: "jeneponto", label: "Kabupaten Jeneponto", province: "Sulawesi Selatan" },
  { value: "takalar", label: "Kabupaten Takalar", province: "Sulawesi Selatan" },
  { value: "kepulauan-selayar", label: "Kabupaten Kepulauan Selayar", province: "Sulawesi Selatan" },
  { value: "soppeng", label: "Kabupaten Soppeng", province: "Sulawesi Selatan" },
  { value: "wajo", label: "Kabupaten Wajo", province: "Sulawesi Selatan" },
  { value: "sidenreng-rappang", label: "Kabupaten Sidenreng Rappang", province: "Sulawesi Selatan" },
  { value: "pinrang", label: "Kabupaten Pinrang", province: "Sulawesi Selatan" },
  { value: "enrekang", label: "Kabupaten Enrekang", province: "Sulawesi Selatan" },
  { value: "luwu", label: "Kabupaten Luwu", province: "Sulawesi Selatan" },
  { value: "luwu-timur", label: "Kabupaten Luwu Timur", province: "Sulawesi Selatan" },
  { value: "luwu-utara", label: "Kabupaten Luwu Utara", province: "Sulawesi Selatan" },
  { value: "tana-toraja", label: "Kabupaten Tana Toraja", province: "Sulawesi Selatan" },
  { value: "toraja-utara", label: "Kabupaten Toraja Utara", province: "Sulawesi Selatan" },

  // ── Sulawesi Tenggara ─────────────────────────────────────────────────────
  { value: "kendari", label: "Kota Kendari", province: "Sulawesi Tenggara" },
  { value: "baubau", label: "Kota Baubau", province: "Sulawesi Tenggara" },
  { value: "konawe", label: "Kabupaten Konawe", province: "Sulawesi Tenggara" },
  { value: "konawe-selatan", label: "Kabupaten Konawe Selatan", province: "Sulawesi Tenggara" },
  { value: "konawe-utara", label: "Kabupaten Konawe Utara", province: "Sulawesi Tenggara" },
  { value: "konawe-kepulauan", label: "Kabupaten Konawe Kepulauan", province: "Sulawesi Tenggara" },
  { value: "kolaka", label: "Kabupaten Kolaka", province: "Sulawesi Tenggara" },
  { value: "kolaka-timur", label: "Kabupaten Kolaka Timur", province: "Sulawesi Tenggara" },
  { value: "kolaka-utara", label: "Kabupaten Kolaka Utara", province: "Sulawesi Tenggara" },
  { value: "bombana", label: "Kabupaten Bombana", province: "Sulawesi Tenggara" },
  { value: "muna", label: "Kabupaten Muna", province: "Sulawesi Tenggara" },
  { value: "muna-barat", label: "Kabupaten Muna Barat", province: "Sulawesi Tenggara" },
  { value: "buton", label: "Kabupaten Buton", province: "Sulawesi Tenggara" },
  { value: "buton-utara", label: "Kabupaten Buton Utara", province: "Sulawesi Tenggara" },
  { value: "buton-selatan", label: "Kabupaten Buton Selatan", province: "Sulawesi Tenggara" },
  { value: "buton-tengah", label: "Kabupaten Buton Tengah", province: "Sulawesi Tenggara" },
  { value: "wakatobi", label: "Kabupaten Wakatobi", province: "Sulawesi Tenggara" },

  // ── Maluku ────────────────────────────────────────────────────────────────
  { value: "ambon", label: "Kota Ambon", province: "Maluku" },
  { value: "tual", label: "Kota Tual", province: "Maluku" },
  { value: "maluku-tengah", label: "Kabupaten Maluku Tengah", province: "Maluku" },
  { value: "seram-bagian-barat", label: "Kabupaten Seram Bagian Barat", province: "Maluku" },
  { value: "seram-bagian-timur", label: "Kabupaten Seram Bagian Timur", province: "Maluku" },
  { value: "maluku-tenggara", label: "Kabupaten Maluku Tenggara", province: "Maluku" },
  { value: "kepulauan-tanimbar", label: "Kabupaten Kepulauan Tanimbar", province: "Maluku" },
  { value: "maluku-barat-daya", label: "Kabupaten Maluku Barat Daya", province: "Maluku" },
  { value: "kepulauan-aru", label: "Kabupaten Kepulauan Aru", province: "Maluku" },
  { value: "buru", label: "Kabupaten Buru", province: "Maluku" },
  { value: "buru-selatan", label: "Kabupaten Buru Selatan", province: "Maluku" },

  // ── Maluku Utara ──────────────────────────────────────────────────────────
  { value: "ternate", label: "Kota Ternate", province: "Maluku Utara" },
  { value: "tidore-kepulauan", label: "Kota Tidore Kepulauan", province: "Maluku Utara" },
  { value: "halmahera-barat", label: "Kabupaten Halmahera Barat", province: "Maluku Utara" },
  { value: "halmahera-utara", label: "Kabupaten Halmahera Utara", province: "Maluku Utara" },
  { value: "halmahera-timur", label: "Kabupaten Halmahera Timur", province: "Maluku Utara" },
  { value: "halmahera-selatan", label: "Kabupaten Halmahera Selatan", province: "Maluku Utara" },
  { value: "halmahera-tengah", label: "Kabupaten Halmahera Tengah", province: "Maluku Utara" },
  { value: "kepulauan-sula", label: "Kabupaten Kepulauan Sula", province: "Maluku Utara" },
  { value: "pulau-morotai", label: "Kabupaten Pulau Morotai", province: "Maluku Utara" },
  { value: "pulau-taliabu", label: "Kabupaten Pulau Taliabu", province: "Maluku Utara" },

  // ── Papua Barat ───────────────────────────────────────────────────────────
  { value: "sorong-kota", label: "Kota Sorong", province: "Papua Barat" },
  { value: "sorong", label: "Kabupaten Sorong", province: "Papua Barat" },
  { value: "sorong-selatan", label: "Kabupaten Sorong Selatan", province: "Papua Barat" },
  { value: "raja-ampat", label: "Kabupaten Raja Ampat", province: "Papua Barat" },
  { value: "tambrauw", label: "Kabupaten Tambrauw", province: "Papua Barat" },
  { value: "maybrat", label: "Kabupaten Maybrat", province: "Papua Barat" },
  { value: "manokwari", label: "Kabupaten Manokwari", province: "Papua Barat" },
  { value: "manokwari-selatan", label: "Kabupaten Manokwari Selatan", province: "Papua Barat" },
  { value: "pegunungan-arfak", label: "Kabupaten Pegunungan Arfak", province: "Papua Barat" },
  { value: "teluk-bintuni", label: "Kabupaten Teluk Bintuni", province: "Papua Barat" },
  { value: "teluk-wondama", label: "Kabupaten Teluk Wondama", province: "Papua Barat" },
  { value: "kaimana", label: "Kabupaten Kaimana", province: "Papua Barat" },
  { value: "fak-fak", label: "Kabupaten Fak-Fak", province: "Papua Barat" },

  // ── Papua ─────────────────────────────────────────────────────────────────
  { value: "jayapura-kota", label: "Kota Jayapura", province: "Papua" },
  { value: "jayapura", label: "Kabupaten Jayapura", province: "Papua" },
  { value: "keerom", label: "Kabupaten Keerom", province: "Papua" },
  { value: "sarmi", label: "Kabupaten Sarmi", province: "Papua" },
  { value: "mamberamo-raya", label: "Kabupaten Mamberamo Raya", province: "Papua" },
  { value: "mamberamo-tengah", label: "Kabupaten Mamberamo Tengah", province: "Papua" },
  { value: "waropen", label: "Kabupaten Waropen", province: "Papua" },
  { value: "kepulauan-yapen", label: "Kabupaten Kepulauan Yapen", province: "Papua" },
  { value: "biak-numfor", label: "Kabupaten Biak Numfor", province: "Papua" },
  { value: "supiori", label: "Kabupaten Supiori", province: "Papua" },
  { value: "nabire", label: "Kabupaten Nabire", province: "Papua" },
  { value: "paniai", label: "Kabupaten Paniai", province: "Papua" },
  { value: "dogiyai", label: "Kabupaten Dogiyai", province: "Papua" },
  { value: "deiyai", label: "Kabupaten Deiyai", province: "Papua" },
  { value: "intan-jaya", label: "Kabupaten Intan Jaya", province: "Papua" },
  { value: "puncak-jaya", label: "Kabupaten Puncak Jaya", province: "Papua" },
  { value: "puncak", label: "Kabupaten Puncak", province: "Papua" },
  { value: "mimika", label: "Kabupaten Mimika", province: "Papua" },
  { value: "asmat", label: "Kabupaten Asmat", province: "Papua" },
  { value: "mappi", label: "Kabupaten Mappi", province: "Papua" },
  { value: "merauke", label: "Kabupaten Merauke", province: "Papua" },
  { value: "boven-digoel", label: "Kabupaten Boven Digoel", province: "Papua" },
  { value: "yahukimo", label: "Kabupaten Yahukimo", province: "Papua" },
  { value: "yalimo", label: "Kabupaten Yalimo", province: "Papua" },
  { value: "lanny-jaya", label: "Kabupaten Lanny Jaya", province: "Papua" },
  { value: "nduga", label: "Kabupaten Nduga", province: "Papua" },
  { value: "tolikara", label: "Kabupaten Tolikara", province: "Papua" },
  { value: "pegunungan-bintang", label: "Kabupaten Pegunungan Bintang", province: "Papua" },
  { value: "jayawijaya", label: "Kabupaten Jayawijaya", province: "Papua" },
];
